# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    # - name: Build and push docker
    #   run: |
    #     docker login creds
    #     docker build -t ./..
    #     docker push
# Ambil dari github action marketplace "github action marketplace"
# Cari di google : "github action marketplace"
#      https://github.com/marketplace?type=actions
#       Cari "docker build push"
#         https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Cara buat secret di github :
        #   - Buka repo, ex: rudikarangloi/github-action
        #   - SETTING -
        #   - SECRET AND VARIABLES - ACTIONS
        #   - NEW REPOSITORY SECRET
        #   - Masukan akun docker.com

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: rudicatsmile2/belajar-cicd:1
        # Repo yang ada di decker hub
        
# Setelah OK commit github dan secara otomatis Action akan berjalan
#   dan pada repo docker otomatis terupdate 